{
 "title": "Solar Energy",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "panel", "label": "panel", "query": { "query": "label_values(panel)" } }
  ]
 },
 "panels": [
  {
   "title": "AC Volts",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "phase_voltage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "AC Watt",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "phase_power", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "AC Ampere",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "phase_current", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Device Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "temperature", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "PowerFactor",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pf", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "AC Energy produced",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "energy_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "AC Frequency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mHz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "frequency", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 1, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "string_power{panel=\"panel_0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 1, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "string_power{panel=\"panel_1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 1, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "string_power{panel=\"panel_2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 1, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "string_power{panel=\"panel_3\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AC Volt",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "phase_voltage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "AC Ampere",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "phase_current", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "AC Watt",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "phase_power", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "temperature", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DC Panel Ampere $panel",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "string_current{panel=~\"$panel\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DC Panel Voltage $panel",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "string_voltage{panel=~\"$panel\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DC Panel Watt $panel",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "string_power{panel=~\"$panel\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DC Panel Energy Daily $panel",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "string_energy_daily{panel=~\"$panel\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}